---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - docker_network_name is defined
      - cloudwatch_region is defined
      - cloudwatch_log_group is defined
      - lidarr_downloads_folder is defined
      - lidarr_music_folder is defined
      - backup_day is defined

- name: Create the dockernetwork
  docker_network:
    name: "{{ docker_network_name }}"

- name: Create the config directory
  file:
    path: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/config"
    state: directory
    mode: 0755

- name: Create app container
  docker_container:
    name: "{{ application_name }}-app"
    image: "linuxserver/lidarr:latest"
    restart_policy: "always"
    pull: true
    log_driver: "awslogs"
    log_options:
      awslogs-region: "{{ cloudwatch_region }}"
      awslogs-group: "{{ cloudwatch_log_group }}"
      awslogs-stream: "{{ application_name }}-app"
    networks:
      - name: "{{ docker_network_name }}"
    ports:
      - 8686:8686
    volumes:
      - "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/config:/config"
      - "{{ lidarr_downloads_folder }}:/downloads"
      - "{{ lidarr_music_folder }}:/music"
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/Madrid"
